[namelist:transport]
adjust_vhv_wind=.false.
dep_pt_stencil_extent=2
equation_form=1,2,2,2,2
ffsl_unity_3d=.false.
horizontal_method=1,1,1,1,1
horizontal_monotone=1,2,1,1,1
log_space=.false.,.false.,.false.,.false.,.false.
oned_reconstruction=.true.
panel_edge_treatment='none'
reversible=.false.,.false.,.false.,.false.,.false.
scheme=1,1,1,1,3
splitting=1,1,1,1,5
theta_dispersion_correction=.false.
vertical_method=1,1,1,1,0
vertical_monotone=1,2,1,1,1
