[namelist:jules_initial]
const_val=0.0,0.0
nvars=2
tpl_name='',''
use_file=.true.,.true.
var='rivers_outflow_rp','rivers_sto_rp'
var_name='',''

[namelist:jules_rivers_props]
is_climatology=.false.,.false.,.false.
nvars=3
use_file=.true.,.true.,.true.
var='direction','sequence','rivers_outflow_number'
var_name='river_routing_direction','river_routing_sequence',
        ='river_number'
